# Generated by Django 5.2.6 on 2025-10-17 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        #('listings', '0013_alter_listing_has_kitchen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='eng_stats', serialize=False, to='listings.listing', verbose_name='Listing')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views count')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Reviews count')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Avg rating')),
            ],
            options={
                'verbose_name': 'Listing stats',
                'verbose_name_plural': 'Listing stats',
            },
        ),
        migrations.CreateModel(
            name='SearchQueryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255, unique=True, verbose_name='Keywords')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Count')),
            ],
            options={
                'verbose_name': 'Search keywords stats',
                'verbose_name_plural': 'Search keywords stats',
            },
        ),
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('session_id', models.CharField(blank=True, max_length=64, verbose_name='Session ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_views', to='listings.listing', verbose_name='Listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Listing view',
                'verbose_name_plural': 'Listing views',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('session_id', models.CharField(blank=True, max_length=64, verbose_name='Session ID')),
                ('keywords', models.CharField(max_length=255, verbose_name='Keywords')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Params')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Search query',
                'verbose_name_plural': 'Search queries',
            },
        ),
    ]
