# Generated by Django 5.2.6 on 2025-10-18 20:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_listing_baby_crib_max_alter_listing_guests_max_and_more'),
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquerystats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchquerystats',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='listingstats',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='listing_stats', serialize=False, to='listings.listing', verbose_name='Listing'),
        ),
    ]
