# Generated by Django 5.2.6 on 2025-10-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('renter', 'Renter'), ('lessor', 'Lessor'), ('admin', 'Admin')], default='renter', max_length=20, verbose_name='Role'),
        ),
    ]
