# Generated by Django 5.2.6 on 2025-10-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('renter', 'Renter'), ('lessor', 'Lessor'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='renter', max_length=20, verbose_name='Role'),
        ),
    ]
