# Generated by Django 5.2.6 on 2025-10-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('renter', 'Renter'), ('lessor', 'Lessor'), ('moderator', 'Moderator'), ('admin', 'Admin')], max_length=20, verbose_name='Role'),
        ),
    ]
