# Generated by Django 5.2.7 on 2025-10-22 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='District')),
                ('country', models.CharField(default='DE', max_length=2, verbose_name='Country')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Currency')),
                ('span_days_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Max Span Days')),
                ('span_days_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Min Span Days')),
                ('rooms', models.PositiveSmallIntegerField(default=1, verbose_name='Rooms')),
                ('guests_max', models.PositiveSmallIntegerField(default=0, verbose_name='Max Guests')),
                ('baby_crib_max', models.PositiveSmallIntegerField(default=0, verbose_name='Max Baby Cribs')),
                ('has_kitchen', models.CharField(choices=[('u', 'Unknown'), ('y', 'Yes'), ('n', 'No')], default='u', max_length=1, verbose_name='Kitchen Available')),
                ('parking_available', models.CharField(choices=[('u', 'Unknown'), ('y', 'Yes'), ('n', 'No')], default='u', max_length=1, verbose_name='Parking Available')),
                ('pets_possible', models.CharField(choices=[('u', 'Unknown'), ('y', 'Yes'), ('n', 'No')], default='u', max_length=1, verbose_name='Pets Possible')),
                ('type_housing', models.CharField(choices=[('villa', 'Villa'), ('house', 'ouse'), ('apartment', 'Apartment'), ('penthouse', 'Penthouse'), ('studio', 'Studio'), ('room', 'Room'), ('other', 'Other')], default='apartment', max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'permissions': [('toggle_active_listing', 'Can activate/deactivate listing'), ('view_inactive_listing', 'Can view inactive listings'), ('view_all_listings', 'Can view all listings (active + inactive)')],
            },
        ),
    ]
