# Generated by Django 5.2.6 on 2025-09-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='DE', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(choices=[('villa', 'Villa'), ('house', 'House'), ('apartment', 'Apartment'), ('penthouse', 'Penthouse'), ('studio', 'Studio'), ('room', 'Room'), ('other', 'Other')], default='apartment', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
            },
        ),
    ]
