# Generated by Django 5.2.7 on 2025-10-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='baby_crib_max',
            new_name='baby_cribs_max',
        ),
    ]
