# Generated by Django 5.2.6 on 2025-10-05 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(default='DE', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.PositiveIntegerField(default=1, verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('villa', 'Villa'), ('house', 'House'), ('apartment', 'Apartment'), ('penthouse', 'Penthouse'), ('studio', 'Studio'), ('room', 'Room'), ('other', 'Other')], default='apartment', max_length=20, verbose_name='Type'),
        ),
    ]
