# Generated by Django 5.2.6 on 2025-10-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='max_baby_crib',
            field=models.PositiveIntegerField(default=0, verbose_name='Max Baby Cribs'),
        ),
        migrations.AddField(
            model_name='listing',
            name='max_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='Max Questions'),
        ),
    ]
