# Generated by Django 5.2.6 on 2025-10-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_max_baby_crib_listing_max_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='max_questions',
        ),
        migrations.AddField(
            model_name='listing',
            name='has_kitchen',
            field=models.BooleanField(default=False, verbose_name='Kitchen Available'),
        ),
        migrations.AddField(
            model_name='listing',
            name='max_guests',
            field=models.PositiveIntegerField(default=0, verbose_name='Max Guests'),
        ),
    ]
