# Generated by Django 5.2.6 on 2025-10-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listing_max_questions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='max_baby_crib',
            new_name='baby_crib_max',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='max_guests',
            new_name='guests_max',
        ),
    ]
