# Generated by Django 5.2.6 on 2025-10-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_rename_max_baby_crib_listing_baby_crib_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='parking_available',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Parking Available'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_kitchen',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Kitchen Available'),
        ),
    ]
