# Generated by Django 5.2.6 on 2025-10-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_parking_available_alter_listing_has_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pets_possible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pets Possible'),
        ),
    ]
