# Generated by Django 5.2.6 on 2025-10-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_pets_possible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'permissions': [('toggle_active_listing', 'Can activate/deactivate listing'), ('view_inactive_listing', 'Can view inactive listings'), ('view_all_listings', 'Can view all listings (active + inactive)')], 'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
    ]
