# Generated by Django 5.2.6 on 2025-10-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_listing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='has_kitchen',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Kitchen Available'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking_available',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Parking Available'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pets_possible',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Pets Possible'),
        ),
    ]
