# Generated by Django 5.2.6 on 2025-10-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_listing_has_kitchen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='has_kitchen',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kitchen Available'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking_available',
            field=models.BooleanField(blank=True, null=True, verbose_name='Parking Available'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pets_possible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Pets Possible'),
        ),
    ]
