# Generated by Django 5.2.6 on 2025-10-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_listing_has_kitchen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='span_days_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Span Days'),
        ),
    ]
