# Generated by Django 5.2.6 on 2025-10-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_listing_span_days_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='baby_crib_max',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Max Baby Cribs'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='guests_max',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Max Guests'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='span_days_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Max Span Days'),
        ),
    ]
