# Generated by Django 5.2.7 on 2025-10-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_listing_baby_crib_max_alter_listing_guests_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='type',
            new_name='type_housing',
        ),
        migrations.AlterField(
            model_name='listing',
            name='has_kitchen',
            field=models.CharField(choices=[('u', 'Unknown'), ('y', 'Yes'), ('n', 'No')], default='u', max_length=1, verbose_name='Kitchen Available'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking_available',
            field=models.CharField(choices=[('u', 'Unknown'), ('y', 'Yes'), ('n', 'No')], default='u', max_length=1, verbose_name='Parking Available'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pets_possible',
            field=models.CharField(choices=[('u', 'Unknown'), ('y', 'Yes'), ('n', 'No')], default='u', max_length=1, verbose_name='Pets Possible'),
        ),
    ]
