# Generated by Django 5.2.7 on 2025-10-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_rename_type_listing_type_housing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='span_days_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Min Span Days'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Price'),
        ),
    ]
