# Generated by Django 5.2.6 on 2025-10-05 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('listings', '0003_alter_listing_city_alter_listing_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_bo_listing_bc826d_idx',
            old_name='bookings_bo_accommo_1783e7_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel_hours',
            field=models.PositiveIntegerField(default=48, help_text='How many hours before 00:00 of start_date cancellation is allowed. 0 = non-refundable.', verbose_name='Hours until cancellation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reason_cancel',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reason cancellation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(default=1, verbose_name='Guests'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='listings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.listing', verbose_name='Listings'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Renter'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
    ]
