# Generated by Django 5.2.6 on 2025-10-10 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_bookings_bo_accommo_1783e7_idx_bookings_bo_listing_bc826d_idx_and_more'),
        #('listings', '0003_alter_listing_city_alter_listing_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_listing_bc826d_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='listings',
        ),
        migrations.AddField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.listing', verbose_name='Listing'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'start_date', 'end_date'], name='bookings_bo_listing_437bd0_idx'),
        ),
    ]
