# Generated by Django 5.2.6 on 2025-10-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_bookings_bo_listing_bc826d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Total cost'),
        ),
    ]
