# Generated by Django 5.2.6 on 2025-10-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='baby_crib',
            field=models.PositiveIntegerField(default=1, verbose_name='Kinds'),
        ),
    ]
