# Generated by Django 5.2.6 on 2025-10-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_baby_crib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='baby_crib',
        ),
        migrations.AddField(
            model_name='booking',
            name='baby_cribs',
            field=models.PositiveIntegerField(default=0, verbose_name='Baby Cribs'),
        ),
        migrations.AddField(
            model_name='booking',
            name='kitchen_needed',
            field=models.BooleanField(default=False, verbose_name='Kitchen needed'),
        ),
    ]
