# Generated by Django 5.2.6 on 2025-10-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_baby_crib_booking_baby_cribs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='parking_needed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Parking needed'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='kitchen_needed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Kitchen needed'),
        ),
    ]
