# Generated by Django 5.2.6 on 2025-10-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_parking_needed_alter_booking_kitchen_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pets',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pets'),
        ),
    ]
