# Generated by Django 5.2.6 on 2025-10-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_pets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('can_approve', 'Can approve bookings'), ('can_decline', 'Can decline bookings'), ('can_complete', 'Can mark bookings as completed'), ('can_cancel', 'Can cancel any booking')]},
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_renter__30d6b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_status_233e96_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_listing_437bd0_idx',
        ),
    ]
