# Generated by Django 5.2.6 on 2025-10-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='kitchen_needed',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Kitchen needed'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='parking_needed',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Parking needed'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pets',
            field=models.BooleanField(blank=True, default=False, null=None, verbose_name='Pets'),
        ),
    ]
