# Generated by Django 5.2.7 on 2025-10-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_kitchen_needed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total cost'),
        ),
    ]
