# Generated by Django 5.2.7 on 2025-10-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_booking_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='kitchen_needed',
            field=models.CharField(choices=[('u', 'Unknown'), ('y', 'Yes'), ('n', 'No')], default='u', max_length=1, verbose_name='Kitchen needed'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='parking_needed',
            field=models.CharField(choices=[('u', 'Unknown'), ('y', 'Yes'), ('n', 'No')], default='u', max_length=1, verbose_name='Parking needed'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pets',
            field=models.CharField(choices=[('u', 'Unknown'), ('y', 'Yes'), ('n', 'No')], default='u', max_length=1, verbose_name='Pets'),
        ),
    ]
