# Generated by Django 5.2.6 on 2025-10-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Is valid'),
        ),
        migrations.AddField(
            model_name='review',
            name='owner_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Owner comment'),
        ),
    ]
