# Generated by Django 5.2.6 on 2025-10-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_is_valid_review_owner_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('owner_comment', 'Can write owner comment'), ('moderate_review', 'Can moderate reviews (is_valid)')]},
        ),
    ]
